version: '3.0'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
    networks:
      - esnet
networks:
  esnet: