version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: mall
      # You can use whatever password you like
      RABBITMQ_DEFAULT_PASS: mall
      # Password for root access
      RABBITMQ_DEFAULT_VHOST: /mall
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./conf/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config